### ISSUE TITLE
Change Branch Name

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/PrepPy#37]
To reuse the branches we created last week and change the branch name:
1. rename local branch
2. check current branch
3. delete previous branch
4. push branch with new name to remote
```
git branch -m <old name> <new name>
git branch -v
git push origin :<old name>
git push --set-upstream origin <new name>
```

**Comment by gptzjs** [comment]
@matthewconnell note that @camadi and @jasmineqyj are using their names in the new branch names together with the function names, but I am not doing this as my function name is too long. You should feel free to do either.
