### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/PrepPy#41]
Make sure the branches names are labelled meaningful things, if not it is hard to navigate and understand. Branches are really messy, should instead keep the branches for each function, and if anything large needs to be changed. I see that this is not implemented for milestone 2's tasks yet even though i had spoken about it with the group in lab. There are multiple readme files on the python repo, as well as descriptions for the same things but different files, please clean that up. For python it's much cleaner than for R. Also use of words, please don't use "Our." Instead use This, so more professional language, less lay language.

**Comment by matthewconnell** [comment]
Hi @andytai7 
> Branches are really messy, should instead keep the branches for each function, and if anything large needs to be changed.
- done
> There are multiple readme files on the python repo
- I only see one Readme, where do you see more?
> as well as descriptions for the same things but different files
- Not sure what is meant by this, can you expand on it?
> please don't use "Our."
- done.

Also, in our grades, we lost marks for Choosing a topic, submission guidelines, mechanics of teamwork document, and function specification; can you give feedback on those?

Cheers
