### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/PrepPy#48]
Just a reminder to have 4 branches. I can only see jasmine’s branch, and a readme branch. 
For the reviewing each other’s code, I don’t really see any pull requests that showed that some part of each team member’s code was reviewed by another peer except for one created by Matthew Connell, but I don’t see anyone reviewing the function only on PrepPy or creating any requests for code review. Please add this.

**Comment by matthewconnell** [comment]
Hi @andytai7 

> Just a reminder to have 4 branches. I can only see jasmine’s branch, and a readme branch.
- I think I overcorrected from last week's overabundance of branches and removed them as they were merged. Will get it right next week.
> For the reviewing each other’s code, I don’t really see any pull requests that showed that some part of each team member’s code was reviewed by another peer except for one created by Matthew Connell, but I don’t see anyone reviewing the function only on PrepPy or creating any requests for code review.
- every code change we did this week had a review by another team member
- for example: https://github.com/UBC-MDS/PrepPy/pull/38 in which George comments on and requests changes for Jasmine's code, then Jasmine changes the code, George approves and merges. Almost every code change went like this
- (For reference and if it helps, I was assigned to review Chima's code, Chima reviewed George's, George reviewed Jasmine's, and Jasmine reviewed mine)

**Comment by gptzjs** [comment]
@andytai7 I don't understand why the other branches which were created are not showing. As you can see in the example below, my PR was sent from my branch `train_test_valid_split`

![image](https://user-images.githubusercontent.com/4149251/76222727-3815bb80-61d8-11ea-8c7d-ceeeee846182.png)

**Comment by gptzjs** [comment]
@andytai7 Same for this example from @camadi 

![image](https://user-images.githubusercontent.com/4149251/76223075-7f9c4780-61d8-11ea-9418-0ec1aff63451.png)

**Comment by andytai7** [comment]
George, please put the right version number, instead of just a link, for submission.

Python code: 
For datatype and onehot:
Need to import pandas as pd, so that pd is not a variable undefined. 

On train_valid_test_split:
Import numpy as np, so that np is not undefined. 

Python Testing:
On python, where is the test for train_valid_test_split?
Tests did not run because syntax on file names. 
All tests failed

R code: 
Good

R Testing: 
Testing files should be in a Testthat folder within a Test folder. There should only be a folder and a file in the Test folder, the file should be testthat.R which you have. At the moment it is messy, onehot, train valid test split (has two files) one with test infront one without. Right now only scaler, and type are in the right place.

**Comment by gptzjs** [comment]
@andytai7 

I had some problems debugging which I was working on right to the deadline that resulted in the problems with train_test_valid_split and its test. They have been addressed in my latest PRs. 

We have copied all the R tests to the Testthat folder
